
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ruby
  pool: 5
  username: XXXXX
  password: XXXXX
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ruby
  pool: 5
  username: XXXXX
  password: XXXXX
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ruby
  pool: 5
  username: XXXXX
  password: XXXXX
  host: localhost